export const GET_USER_JOBS_REQUEST = 'GET_USER_JOBS_REQUEST'
export const GET_USER_JOBS_SUCCESS = 'GET_USER_JOBS_SUCCESS'
export const GET_USER_JOBS_FAIL = 'GET_USER_JOBS_FAIL'

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST' 
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS' 
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL' 

export const EXPLORE_JOBS_REQUEST = 'EXPLORE_JOBS_REQUEST' 
export const EXPLORE_JOBS_SUCCESS = 'EXPLORE_JOBS_SUCCESS' 
export const EXPLORE_JOBS_FAIL = 'EXPLORE_JOBS_FAIL'
