export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST'
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS'
export const CREATE_SERVICE_FAIL = 'CREATE_SERVICE_FAIL'

export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST'
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS'
export const EDIT_SERVICE_FAIL = 'EDIT_SERVICE_FAIL'

export const EXPLORE_SERVICES_REQUEST = 'EXPLORE_SERVICES_REQUEST'
export const EXPLORE_SERVICES_SUCCESS = 'EXPLORE_SERVICES_SUCCESS' 
export const EXPLORE_SERVICES_FAIL = 'EXPLORE_SERVICES_FAIL' 

