export const GET_SINGLE_USER_REQUEST = 'GET_SINGLE_USER_REQUEST'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_FAIL = 'GET_SINGLE_USER_FAIL'

export const EDIT_USER_INFO_REQUEST = 'EDIT_USER_INFO_REQUEST'
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS'
export const EDIT_USER_INFO_FAIL = 'EDIT_USER_INFO_FAIL'